### ISSUE TITLE
Use Alexis King's struct-id syntax class instead of unstable get-struct-info

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/kw-make-struct#2]
Use Alexis King's [`struct-id`][struct-id] syntax class instead of get-struct-info from `unstable/struct`.

  [struct-id]: http://docs.racket-lang.org/syntax-classes/index.html?q=struct-id#%28form._%28%28lib._syntax%2Fparse%2Fclass%2Fstruct-id..rkt%29._struct-id%29%29

**Comment by stchang** [comment]
yay
